### ISSUE TITLE
Merge AES-128 PR #75

### ISSUE THREAD

**Issue by onizet** [jmanm/PDFsharp-netstandard2.0#4]
Hello,

First thank you for your nuget package. This was really helpful and finally, a PdfSharp version that work without problems on netcore!

My requirement is to protect a PDF to be unlocked with [free online tool](https://www.ilovepdf.com/unlock_pdf).
After some testing, the site was unable to crack a 32-char random password when the file is encrypted with AES-128, but make it very easy with the basic RCA4-128 as implemented by default.

I will be very happy if you can merge this [PR#75](https://github.com/empira/PDFsharp/pull/75) into your fork and republish a nuget version.
Do you think it's feasible?

To reproduce the protection, you can use the underlying code
```c#
var securitySettings = pdfDocument.SecuritySettings;
securitySettings.PermitAnnotations = false;
securitySettings.PermitAssembleDocument = false;
securitySettings.PermitExtractContent = false;
securitySettings.PermitFormsFill = true;
securitySettings.PermitFullQualityPrint = false;
securitySettings.PermitModifyDocument = false;
securitySettings.PermitPrint = false;

securitySettings.OwnerPassword = password;
securitySettings.DocumentSecurityLevel =
    PdfSharp.Pdf.Security.PdfDocumentSecurityLevel.Encrypted128BitAes;
```

**Comment by jmanm** [comment]
Hi @onizet sorry for the slow reply. This definitely likes like a useful PR. I'll have a look and see if it can be easily merged in.

**Comment by jmanm** [comment]
@onizet I have reviewed the code and merged the PR. The new nuget package (version 1.2.0) should be up shortly. Thanks again for alerting me to this.
